daemon off;

events {
    worker_connections 1024; 
}

http {
    error_log  /dev/stderr debug;
    access_log /dev/stdout;
    resolver 8.8.8.8 ipv6=off;

    upstream backend {
        server 127.0.0.1:10001 max_fails=1 fail_timeout=1;          # USER_IDC_CLUSTER_ENDPOINT
        server 127.0.0.1:10002 max_fails=100 fail_timeout=1 backup; # USER_FC_CLUSTER_ENDPOINT
    }

    server {
        listen 10001;
        location / {
            #proxy_pass ${USER_IDC_CLUSTER_ENDPOINT};
        }
    }

    server {
        listen 10002;
        location / {
            #proxy_pass ${USER_FC_CLUSTER_ENDPOINT};
        }
    }

    server {
        listen 9000;
        location / {
            proxy_pass http://backend;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504 http_429 non_idempotent;
            proxy_request_buffering on;
            proxy_connect_timeout 60s;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;
            proxy_next_upstream_tries 10;

            #proxy_method POST;
            #proxy_next_upstream error timeout http_500 http_502 http_503 http_504 http_429;
            #proxy_next_upstream_timeout 2s;   
            #client_max_body_size 1m;
            #proxy_bind $remote_addr transparent;
            #proxy_bind off;
            #proxy_set_header Host $proxy_host;
            #proxy_set_header X-Real-IP $remote_addr;
            #proxy_set_header X-Forwarded-Method $request_method;
            #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            #proxy_set_header X-Forwarded-Proto $scheme;
            #proxy_socket_keepalive off;
            
        }
    }
}
